 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lessons_started_by_user", type: :request do
  
  # LessonStartedByUser. As you add validations to LessonStartedByUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LessonStartedByUser.create! valid_attributes
      get lessons_started_by_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lesson_started_by_user = LessonStartedByUser.create! valid_attributes
      get lesson_started_by_user_url(lesson_started_by_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lesson_started_by_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      lesson_started_by_user = LessonStartedByUser.create! valid_attributes
      get edit_lesson_started_by_user_url(lesson_started_by_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LessonStartedByUser" do
        expect {
          post lessons_started_by_user_url, params: { lesson_started_by_user: valid_attributes }
        }.to change(LessonStartedByUser, :count).by(1)
      end

      it "redirects to the created lesson_started_by_user" do
        post lessons_started_by_user_url, params: { lesson_started_by_user: valid_attributes }
        expect(response).to redirect_to(lesson_started_by_user_url(LessonStartedByUser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LessonStartedByUser" do
        expect {
          post lessons_started_by_user_url, params: { lesson_started_by_user: invalid_attributes }
        }.to change(LessonStartedByUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post lessons_started_by_user_url, params: { lesson_started_by_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lesson_started_by_user" do
        lesson_started_by_user = LessonStartedByUser.create! valid_attributes
        patch lesson_started_by_user_url(lesson_started_by_user), params: { lesson_started_by_user: new_attributes }
        lesson_started_by_user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lesson_started_by_user" do
        lesson_started_by_user = LessonStartedByUser.create! valid_attributes
        patch lesson_started_by_user_url(lesson_started_by_user), params: { lesson_started_by_user: new_attributes }
        lesson_started_by_user.reload
        expect(response).to redirect_to(lesson_started_by_user_url(lesson_started_by_user))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        lesson_started_by_user = LessonStartedByUser.create! valid_attributes
        patch lesson_started_by_user_url(lesson_started_by_user), params: { lesson_started_by_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lesson_started_by_user" do
      lesson_started_by_user = LessonStartedByUser.create! valid_attributes
      expect {
        delete lesson_started_by_user_url(lesson_started_by_user)
      }.to change(LessonStartedByUser, :count).by(-1)
    end

    it "redirects to the lessons_started_by_user list" do
      lesson_started_by_user = LessonStartedByUser.create! valid_attributes
      delete lesson_started_by_user_url(lesson_started_by_user)
      expect(response).to redirect_to(lessons_started_by_user_url)
    end
  end
end
